# Generated by Django 4.2.14 on 2024-08-18 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20, verbose_name='FirstName')),
                ('SecondName', models.CharField(max_length=20, verbose_name='SecondName')),
                ('serve', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='serve')),
                ('attack', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='attack')),
                ('keep_ball', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='keep_ball')),
                ('comand_game', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='comand_game')),
            ],
            options={
                'verbose_name': 'Гравці',
                'verbose_name_plural': 'Гравці',
            },
        ),
        migrations.CreateModel(
            name='Web_admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_admin', models.CharField(max_length=20, verbose_name='login_admin')),
                ('password_admin', models.CharField(max_length=20, verbose_name='password_admin')),
            ],
            options={
                'verbose_name': 'Адміністратори',
                'verbose_name_plural': 'Адміністратори',
            },
        ),
        migrations.CreateModel(
            name='СoefficientsOfCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serve_coef', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='serve')),
                ('attack_coef', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='attack')),
                ('keep_ball_coef', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='keep_ball')),
                ('team_game_coef', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='team_game')),
            ],
            options={
                'verbose_name': 'Коєфіцієнти',
                'verbose_name_plural': 'Коєфіцієнти',
            },
        ),
    ]
