# Generated by Django 4.2.14 on 2024-08-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сoefficientsofcharacteristics',
            options={},
        ),
    ]
